import { test, expect } from 'playwright/test';
const baseURL = `https://${process.env.REPLIT_DEV_DOMAIN}`;
test.use({ baseURL, storageState: 'tmp-storage.json', ignoreHTTPSErrors: true, timezoneId: 'UTC' });
test('super admin routing', async ({ page }) => {
  page.on('console', m => console.log('CONSOLE', m.type(), m.text()));
  page.on('pageerror', e => console.log('PAGEERROR', e.message));
  page.on('requestfailed', r => console.log('REQFAILED', r.url(), r.failure()?.errorText));
  await page.goto('/');
  await page.waitForURL(/\/platform-admin$/);
  await expect(page.getByRole('heading', { name: 'إدارة المنصة' })).toBeVisible();
  await expect(page.getByText('العيادات والمراكز')).toBeVisible();
  const trialRow = page.getByRole('row').filter({ hasText: 'فترة تجريبية' }).first();
  await expect(trialRow).toBeVisible();
  await trialRow.click();
  await expect(page.getByRole('heading', { name: 'إجراءات الحساب' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'تمديد التجربة' })).toBeVisible();
  await page.screenshot({ path: 'tmp-platform-admin.png', fullPage: true });
  await page.goto('/access-status');
  await page.waitForURL(/\/platform-admin$/);
  await expect(page.getByRole('heading', { name: 'إدارة المنصة' })).toBeVisible();
});
