type ExportLocale = "ar" | "en";

const ENGLISH_EXPORT_VALUES: Record<string, string> = {
  "حالة جديدة": "New case",
  "تمت الزراعة": "Implant placed",
  "مرحلة الالتئام": "Healing phase",
  "تحت المتابعة": "Under follow-up",
  "يحتاج تواصل": "Contact needed",
  "جاهز للتركيب": "Ready for prosthesis",
  "تم تحديد موعد التركيب": "Prosthetic appointment set",
  "تم تركيب مؤقت": "Temporary prosthesis placed",
  "تحويل المؤقت إلى دائم": "Convert temporary to final",
  "تم التركيب": "Prosthesis placed",
  "مؤجل": "Postponed",
  "لم يحضر": "No-show",
  "منقطع": "Discontinued",
  "زرعة فاشلة": "Failed implant",
  "يحتاج إعادة زراعة": "Needs reimplantation",
  "تمت إعادة الزراعة": "Reimplanted",
  "استكمال العلاج في عيادة أخرى": "Treatment continued elsewhere",
  "مكتمل": "Complete",
  "مزروعة": "Implanted",
  "جاهزة للتركيب": "Ready for prosthesis",
  "فاشلة": "Failed",
  "تحتاج إعادة": "Needs reimplantation",
  "مؤرشفة": "Archived",
  "دفعة أولى": "First payment",
  "دفعة ثانية": "Second payment",
  "دفعة كاملة": "Full payment",
  "دفعة إضافية": "Additional payment",
  "شبكة": "Card",
  "نقدي": "Cash",
  "تحويل": "Bank transfer",
  "تمارا": "Tamara",
  "أخرى": "Other",
  "لم يدفع": "Unpaid",
  "مدفوع جزئيًا": "Partially paid",
  "مدفوع بالكامل": "Paid in full",
  "رصيد زائد": "Overpaid",
  "مؤجل ماليًا": "Financially deferred",
  "مدفوع": "Paid",
  "مستحق اليوم": "Due today",
  "متأخر": "Overdue",
  "مجدول": "Scheduled",
  "متابعة بعد العملية": "Post-operative follow-up",
  "تقييم ثبات الزرعة": "Implant stability assessment",
  "أشعة": "X-ray",
  "جاهزية للتركيب": "Prosthetic readiness",
  "موعد تركيب": "Prosthetic appointment",
  "متابعة المؤقت": "Temporary prosthesis follow-up",
  "متابعة زراعة العظم": "Bone graft follow-up",
  "متابعة رفع الجيب الأنفي": "Sinus lift follow-up",
  "متابعة زرعة فاشلة": "Failed implant follow-up",
  "إعادة زراعة": "Reimplantation",
  "متابعة مالية": "Financial follow-up",
  "تواصل عام": "General contact",
  "مجدولة": "Scheduled",
  "تمت": "Completed",
  "مؤجلة": "Postponed",
  "لا يوجد رد": "No response",
  "تحتاج إعادة تواصل": "Needs re-contact",
  "ملغاة": "Cancelled",
  "تم فتح واتساب": "WhatsApp opened",
  "تم التواصل": "Contacted",
  "أكد الموعد": "Appointment confirmed",
  "طلب تغيير الموعد": "Requested appointment change",
  "سيتم التواصل لاحقًا": "Will contact later",
  "رقم غير صحيح": "Invalid number",
  "تذكير بالموعد": "Appointment reminder",
  "متابعة زراعة": "Implant follow-up",
  "استكمال العلاج": "Complete treatment",
  "موعد فائت": "Missed appointment",
  "متابعة بعد الإجراء": "Post-procedure follow-up",
  "تذكير مالي عام": "General payment reminder",
  "زراعة عظم": "Bone graft",
  "رفع جيب أنفي": "Sinus lift",
  "مؤقت": "Temporary prosthesis",
  "إجراء إضافي": "Additional procedure",
  "ضريبة": "Tax",
  "رفع الجيب الفكي": "Maxillary sinus lift",
  "إبعاد / نقل العصب السنخي السفلي": "Inferior alveolar nerve repositioning",
  "يمين": "Right",
  "يسار": "Left",
  "مفتوح": "Open",
  "مغلق": "Closed",
  "تركيب مؤقت": "Temporary prosthesis",
  "تركيب دائم": "Final prosthesis",
};

export function localizeExportValue<T>(
  value: T,
  locale: ExportLocale,
): T | string {
  if (locale === "ar" || typeof value !== "string") return value;
  return ENGLISH_EXPORT_VALUES[value] ?? value;
}

export function localizeExportList(
  values: string[],
  locale: ExportLocale,
): string {
  return values
    .map((value) => localizeExportValue(value, locale))
    .join(locale === "ar" ? "، " : ", ");
}