const admin = {
  settings: { title: "Settings", tabs: { users: "Users", lookups: "Lists", audit: "Activity log", export: "Export data" }, systemTitle: "System settings", clinicName: "Clinic name", systemName: "System name (in header)", defaultTreatingDoctor: "Default treating doctor", clinicPhone: "Clinic phone (optional)", defaultProsValue: "Default Pros value (optional)", defaultFollowupAssignee: "Default follow-up assignee (optional)", noDefault: "No default", clinicAddress: "Clinic address (optional)", clinicLogo: "Clinic logo", defaultLogoInUse: "The default logo is currently in use.", uploadLogo: "Upload logo", removeLogo: "Remove logo", logoHelp: "PNG, JPEG, or WebP, up to 500 KB.", save: "Save settings", saveSuccess: "Settings saved successfully.", saveFailed: "Could not save settings", logoFormatUnsupportedTitle: "Unsupported logo format", logoFormatUnsupportedDescription: "Choose a PNG, JPEG, or WebP image.", logoTooLargeTitle: "Logo file is too large", logoTooLargeDescription: "The maximum size is 500 KB." },
  templates: { title: "WhatsApp message templates", description: "Messages are opened manually through WhatsApp (wa.me) — there is no automatic sending. Supported placeholders:", active: "Active", inactive: "Inactive", edit: "Edit", activate: "Activate", deactivate: "Deactivate", editTitle: "Edit template: {{name}}", name: "Template name", messageBody: "Message text", preview: "Preview with sample data", save: "Save template", cancel: "Cancel", placeholderLabels: { patientName: "Patient name", date: "Date", time: "Time" }, operationFailed: "Could not complete the operation", saveSuccess: "Template saved.", unknownPlaceholders: "Unknown placeholders: {{unknown}} — only these placeholders are supported: {{supported}}" },
  import: { title: "Import legacy data (CSV)", safetyNotice: "Importing is always safe: preview does not write anything to the database, and import never replaces or modifies an existing record — duplicate records are skipped or rejected according to the selected mode.", dataType: "Data type", duplicateHandling: "Duplicate handling", skipDuplicates: "Skip duplicate records", createOnly: "Reject file if it contains duplicates (create only)", readyTemplate: "Ready-made template", downloadTemplate: "Download {{type}} template", chooseFile: "Choose CSV file", preview: "Preview (without saving)", totalRows: "Total rows: {{count}}", valid: "Valid: {{count}}", duplicate: "Duplicates: {{count}}", invalid: "Invalid: {{count}}", confirmImport: "Confirm import ({{count}} records)", cancel: "Cancel", commitSummary: "Import complete: imported {{imported}} records, skipped {{skipped}}, and failed {{failed}}.", row: "Row", status: "Status", summary: "Summary", errors: "Errors", truncated: "Only some rows are displayed for brevity.", statuses: { valid: "Valid", invalid: "Invalid", duplicate: "Duplicate" }, types: { patients: "Patients", cases: "Implant cases", implants: "Implants", payments: "Payments", charges: "Additional charges", discounts: "Discounts", followups: "Follow-ups", communications: "Communication log" }, operationFailed: "Could not complete the operation", fileTooLargeTitle: "File is too large", fileTooLargeDescription: "The maximum size is 4 MB.", completedTitle: "Import complete.", completedDescription: "Imported {{imported}} records, skipped {{skipped}}, and failed {{failed}}." },
  users: {
    title: "User management", newUser: "New user", fullName: "Full name", username: "Username", email: "Recovery email", role: "Role", status: "Status", viewFinancials: "View financial data", recordPayments: "Record payments", lastLogin: "Last login",
    active: "Active", suspended: "Suspended", yes: "Yes", no: "No", edit: "Edit", deactivate: "Deactivate", activate: "Activate", resetPassword: "Reset password",
    retentionNotice: "Users cannot be deleted to preserve historical records; they can only be deactivated. Deactivating a user immediately prevents sign-in while keeping all of their records visible.", avatarHelp: "For the best appearance, use an image with a transparent background.",
    operationFailed: "Could not complete the operation", unexpectedError: "An unexpected error occurred.", avatar: "Profile picture", created: "User created successfully.", saved: "Changes saved.", passwordReset: "Password reset.", passwordResetDescription: "The user's current sessions were ended and they will need to sign in again.", deactivated: "User deactivated and their sessions ended.", activated: "User reactivated.",
    createTitle: "New user", usernameLogin: "Username (for sign-in)", recoveryEmail: "Recovery email", temporaryPassword: "Temporary password", passwordHint: "At least 12 characters, including a letter and a number.", create: "Create user",
    editTitle: "Edit user {{name}}", legacyEmailNotice: "This is a legacy account without a recovery email. Add and save a valid email to enable recovery.", permissionNotice: "Permission changes apply immediately to the user's current sessions.", saveChanges: "Save changes",
    resetTitle: "Reset password for {{name}}", newPassword: "Temporary password (Optional)", resetHint: "Leave blank to generate a secure password. Current sessions will end and the user must change it at next sign-in.", reset: "Reset", temporaryPasswordNotice: "Copy this temporary password now and share it manually. It cannot be viewed again after closing this dialog.", copyPassword: "Copy password",
    permissionDefault: "Role default", allowed: "Allowed", denied: "Not allowed",
  },
  lookup: {
    title: "Dropdown list management", category: "Category", newValue: "New value…", add: "Add", order: "Order", value: "Value", status: "Status", actions: "Actions", empty: "There are no options in this category yet.",
    active: "Active", suspended: "Inactive", referenced: "Used in records", referencedTitle: "Historical records use this value", moveUp: "Move up", moveDown: "Move down", rename: "Click to rename", deactivate: "Deactivate", activate: "Activate", delete: "Delete",
    operationFailed: "Could not complete the operation", unexpectedError: "An unexpected error occurred.", added: "Option added.", renamed: "Option renamed.", renameDescription: "Historical records retain their original value.", deleted: "Option deleted.",
    deleteReferenced: "This option cannot be deleted because records use it. You can deactivate it instead.", retentionNotice: "Deactivating an option only hides it from new lists; historical records remain unchanged. Deletion is available only for options unused in any record.",
    categories: { implant_system: "Implant systems", q_value: "Q options", former_value: "Former options", graft_value: "Graft options", procedure_tag: "Procedure tags", bone_graft_procedure_type: "Bone graft procedure types", bone_graft_material: "Bone graft materials", bone_graft_membrane: "Bone graft membranes", bone_graft_status: "Bone graft procedure statuses" },
  },
  audit: {
    recent: "Recent activity", title: "Activity log", exportCsv: "Export CSV", from: "From date", to: "To date", user: "User", action: "Action", entityType: "Record type", fileNumber: "File number", all: "All", fileNumberPlaceholder: "Example: 1001",
    time: "Time", description: "Description", empty: "No records match the selected filters.", total: "Total records: {{count}}", previous: "Previous", next: "Next", page: "Page {{page}} of {{totalPages}}",
    actions: { patient_create: "Patient added", patient_update: "Patient details updated", patient_archive: "Patient file archived", patient_restore: "Patient file restored", implant_case_create: "Implant case added", implant_case_update: "Implant case updated", implant_create: "Implant added", implant_update: "Implant updated", case_base_amount_update: "Treatment amount updated", payment_create: "Payment recorded", payment_void: "Payment voided", followup_created: "Follow-up added", followup_updated: "Follow-up updated", followup_completed: "Follow-up completed", user_create: "User created", login_success: "Signed in" },
  },
  export: { title: "Data Export", description: "Export your organization data as professionally formatted PDF or Excel files.", entities: { patients: "Patients", cases: "Implant cases", implants: "Implants", payments: "Payments", charges: "Additional charges", discounts: "Discounts", followups: "Follow-ups", communications: "Communication log" } },
} as const;
export default admin;